config/routes.rb
Rails.application.routes.draw do
  resources :regions
  resources :schedules do
    collection { post :import }
  end

  root to: 'visitors#index'
end

app/models/region.rb
class Region < ActiveRecord::Base
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  searchkick text_start: [:affected_areas]

  Schedule.reindex

  scope :by_region, -> region { where(region: region)}

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Schedule.create! row.to_hash
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  before_action :set_region, only: [:show, :edit, :update, :destroy]

  # GET /regions
  # GET /regions.json
  def index
    @regions = Region.all
  end

  # GET /regions/1
  # GET /regions/1.json
  def show
  end

  # GET /regions/new
  def new
    @region = Region.new
  end

  # GET /regions/1/edit
  def edit
  end

  # POST /regions
  # POST /regions.json
  def create
    @region = Region.new(region_params)

    respond_to do |format|
      if @region.save
        format.html { redirect_to @region, notice: 'Region was successfully created.' }
        format.json { render :show, status: :created, location: @region }
      else
        format.html { render :new }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /regions/1
  # PATCH/PUT /regions/1.json
  def update
    respond_to do |format|
      if @region.update(region_params)
        format.html { redirect_to @region, notice: 'Region was successfully updated.' }
        format.json { render :show, status: :ok, location: @region }
      else
        format.html { render :edit }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /regions/1
  # DELETE /regions/1.json
  def destroy
    @region.destroy
    respond_to do |format|
      format.html { redirect_to regions_url, notice: 'Region was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_region
      @region = Region.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def region_params
      params.require(:region).permit(:region, :region_code)
    end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  require 'date'
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  def autocomplete
    render json: Schedule.search(params[:query], fields: [{affected_areas: :text_start}], limit: 10).map(&:affected_areas)
  end

  # GET /schedules
  # GET /schedules.json
  def index
    t = Date::DAYNAMES[Date.today.wday]
    # Date.today.wday
    if params[:region] == "lsk" then
      my_region = "Lusaka Division"
    elsif params[:region] == "cb" then
      my_region = "Copperbelt Divison"
    elsif params[:region] == "nd" then
      my_region = "Northern Division"
    elsif params[:region] == "sd" then
      my_region = "Southern Division"
    end

    @schedules = Schedule.by_region(my_region).where("day LIKE '%#{t}%'").order(region: :asc, start_time: :asc).search "milk", page: params[:page],per_page: 20
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    @schedule = Schedule.import(params[:file])
    redirect_to schedules_url, notice: "Schedules added successfully"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:day, :start_time, :end_time, :region, :city, :affected_areas)
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/loads_helper.rb
module LoadsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Loadsched', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<%= link_to 'Help', page_path('help') %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Loadshed.Co'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Loadsheding in Zambia ZESCO schedule'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      .container
        = render 'layouts/messages'
        = yield
    %footer

app/views/regions/_form.html.haml
= simple_form_for(@region) do |f|
  = f.error_notification

  .form-inputs
    = f.input :region
    = f.input :region_code

  .form-actions
    = f.button :submit

app/views/regions/edit.html.haml
%h1 Editing region

= render 'form'

= link_to 'Show', @region
\|
= link_to 'Back', regions_path

app/views/regions/index.html.haml
%h1 Listing regions

.media
  .media-body
    %table.table.table-hover
      %thead
        %tr
          %th Region
          %th Region code
          %th
          %th
          %th

      %tbody
        - @regions.each do |region|
          %tr
            %td= region.region
            %td= region.region_code
            %td= link_to 'Show', region
            %td= link_to 'Edit', edit_region_path(region)
            %td= link_to 'Destroy', region, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Region', new_region_path

app/views/regions/new.html.haml
%h1 New region

= render 'form'

= link_to 'Back', regions_path

app/views/regions/show.html.haml
%p#notice= notice

%p
  %b Region:
  = @region.region
%p
  %b Region code:
  = @region.region_code

= link_to 'Edit', edit_region_path(@region)
\|
= link_to 'Back', regions_path

app/views/schedules/_form.html.haml
= simple_form_for(@schedule) do |f|
  = f.error_notification

  .form-inputs
    = f.input :day
    = f.input :start_time
    = f.input :end_time
    = f.input :region
    = f.input :city
    = f.input :affected_areas

  .form-actions
    = f.button :submit

app/views/schedules/edit.html.haml
%h1 Editing schedule

= render 'form'

= link_to 'Show', @schedule
\|
= link_to 'Back', schedules_path

app/views/schedules/index.html.haml
%h1 Today's schedule

%input#query{ :type => 'text', :name => 'query' }
%javascript{ :src=> 'jquery.js' }
%javascript{ :src=> 'typeahead.js' }

%javascript
  $("#query").typeahead({
  name: "city",remote: "/schedules/autocomplete?region=%QUERY"
  });

regions = { :LSK => "Lusaka Division"}

%ul.nav.nav-tabs.nav-justified
  -# - @regions.each do |region|
  %li.active{ :role => 'presentation' }
    = link_to "Lusaka", 'schedules?region=lsk'
    .media
      .media-body
        %table.table.table-hover
          %thead
            %tr
              -# %th Day
              %th Start time
              %th End time
              -# %th Region
              %th City
              %th Affected areas
              %th
              %th
              %th

          %tbody
            - @schedules.each do |schedule|
              %tr
                -# %td= schedule.day
                %td= schedule.start_time.strftime("%H:%M")
                %td= schedule.end_time.strftime("%H:%M")
                -# %td= schedule.region
                %td= schedule.city
                %td= schedule.affected_areas
                -# %td= link_to 'Show', schedule
                -# %td= link_to 'Edit', edit_schedule_path(schedule)
                -# %td= link_to 'Destroy', schedule, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

%h3 Import Schedules
-# =simple_form_for @schedules, :url => import_schedules_path, :html => { :multipart => true } do
-#   =f.error_notification
-#   =f.f.input :file
-#   =f.submit "Import"

=form_tag import_schedules_path, multipart: true do
  =file_field_tag :file
  =submit_tag "Upload Schedules"

= link_to 'New Schedule', new_schedule_path

app/views/schedules/new.html.haml
%h1 New schedule

= render 'form'

= link_to 'Back', schedules_path

app/views/schedules/show.html.haml
%p#notice= notice

%p
  %b Day:
  = @schedule.day
%p
  %b Start time:
  = @schedule.start_time
%p
  %b End time:
  = @schedule.end_time
%p
  %b Region:
  = @schedule.region
%p
  %b City:
  = @schedule.city
%p
  %b Affected areas:
  = @schedule.affected_areas

= link_to 'Edit', edit_schedule_path(@schedule)
\|
= link_to 'Back', schedules_path

app/views/visitors/index.html.haml
%h1.lead Find out it if your area is under loadshedding at the moment.

-# =simple_form_for @visitor do |e|
-#   =f.input :search, placeholder: 'Search for your area'
-#   =f.button :butto, "Search"